### PR TITLE
Generate module for d3

### PR DESCRIPTION
**Pull request by offirgolan**
Resolves offirgolan/ember-cli-nvd3#10

/ping @mike-north

### CODE REVIEW

**Comment by mike-north** [comment]
I wonder why ember-d3 isn't taking care of this

**Comment by offirgolan** [comment]
We removed the ember-d3 dependency since we had to make sure d3 v3 is
installed to support the current nvd3 version.

**Comment by mike-north** [comment]
We were adding a v3 bower dependency in the installation blueprint. How is it possible to get a version other than `3.*`?

**Comment by offirgolan** [comment]
From what I remember (currently away from my laptop) we replaced ember-d3
add-on with d3 bower package

**Comment by mike-north** [comment]
Let's set some time aside to think through this. Seems like we may be making things more complicated and redundant than necessary

**Comment by offirgolan** [comment]
Agreed but as of right now ember-cli-nvd3 is unusable until this has been
resolved. I suggest to merge this, create a patch release to unblock
upstream, and open an issue on here to open up the discussion for a better
solution.

**Comment by mike-north** [comment]
Per discussion w/ @offirgolan on slack, this is not the approach that will serve the ecosystem best. Working on a more wholistic approach that separates concerns nicely (d3 stuff existing only in `ember-d3`, etc...)

**Pull request closed without merging**
